name: Build and deploy docker image

on:
  push:
    branches: [ master ]

jobs:
  build_and_publish_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - id: build_docker
        run: |
          echo $GITHUB_TOKEN | docker login -u $GITHUB_ACTOR --password-stdin docker.pkg.github.com
          docker build -t docker.pkg.github.com/carumusan/substrate-builder/edgeware:3.0.1 .
          docker push docker.pkg.github.com/carumusan/substrate-builder/edgeware:3.0.1
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
