name: Build and deploy docker image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Edgeware Version'
        required: true
        default: 'v3.3.5'
jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/edgeware.Dockerfile
          push: true
          tags: |
            ghcr.io/tsukistaking/edgeware::${{ github.event.inputs.version }}
            ghcr.io/tsukistaking/edgeware:latest
          build-args: |
             VERSION=:${{ github.event.inputs.version }}
