name: Build and deploy docker image

on:
  push:
    paths:
      - '**edgeware.Dockerfile'
      - '**/edgeware-docker-publish.yml'
jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        env:
          EDGEWARE_VERSION: v3.3.1
        with:
          context: .
          file: docker/edgeware.Dockerfile
          push: true
          tags: |
            ghcr.io/tsukistaking/edgeware:${{ env.EDGEWARE_VERSION }}
            ghcr.io/tsukistaking/edgeware:latest
          build-args: |
             VERSION=${{ env.EDGEWARE_VERSION }}
