name: Polkadot Docker Build and Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Polkadot Version'
        required: true
        default: 'v0.9.11'
jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/polkadot.Dockerfile
          push: true
          tags: |
            ghcr.io/tsukistaking/polkadot:${{ github.event.inputs.version }}
            ghcr.io/tsukistaking/polkadot:latest
          build-args: |
             VERSION=${{ github.event.inputs.version }}
      - name: Call Polkadot Rollout Action
        run: |
          python dispatch_rollout_action.py
        env:
          GHUB_USERNAME: ${{ secrets.GHUB_USERNAME }}
          GHUB_ACCESS_TOKEN: ${{ secrets.GHUB_ACCESS_TOKEN }}
